version: "3.2"
services:
  database:
    image: "postgres:latest"
    container_name: "person_database"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "person_db"